import {test} from 'node:test';
import assert from 'node:assert/strict';
import {runProductionSmoke,smokeSummary} from '../../scripts/production-smoke.ts';
const origin='https://champion.example',sha='a'.repeat(40);
function fixture(url:string){const path=new URL(url).pathname;if(path==='/api/health')return new Response(JSON.stringify({status:'ok',check:'configuration_only',release:sha,accounts:true,scheduled_jobs:true,payments:false,email_delivery_enabled:false,monitoring:false}),{headers:{'content-type':'application/json'}});if(path==='/portal'||path==='/admin')return new Response(null,{status:307,headers:{location:path==='/admin'?'/admin/login':'/login'}});if(path.startsWith('/api/'))return new Response('{}',{status:401});return new Response('<html>Champion</html>',{headers:{'content-type':'text/html','x-frame-options':'DENY','x-content-type-options':'nosniff'}});}
test('production availability can pass without falsely claiming provider launch readiness',async()=>{const result=await runProductionSmoke({origin,expectedRelease:sha,fetcher:async url=>fixture(url)});assert.equal(result.ok,true);assert.equal(result.checks.length,10);assert.equal(result.pendingConfiguration.length,3);assert.match(smokeSummary(result),/customer launch acceptance remain separate/);});
test('production check catches release mismatch and accidental anonymous billing exposure',async()=>{const result=await runProductionSmoke({origin,expectedRelease:'b'.repeat(40),fetcher:async url=>url.endsWith('/api/engagement-billing')?new Response('{}'):fixture(url)});assert.equal(result.ok,false);assert.deepEqual(result.checks.filter(c=>!c.ok).map(c=>c.path),['/api/engagement-billing','/api/health']);});
test('production check rejects offsite redirects and missing security headers',async()=>{const result=await runProductionSmoke({origin,fetcher:async url=>url.endsWith('/admin')?new Response(null,{status:307,headers:{location:'https://attacker.example/admin/login'}}):url.endsWith('/login')?new Response('Champion',{headers:{'content-type':'text/html'}}):fixture(url)});assert.equal(result.ok,false);assert.equal(result.checks.find(c=>c.path==='/admin')?.ok,false);assert.equal(result.checks.find(c=>c.path==='/login')?.ok,false);});
test('production check fails on outage without copying provider error details into reports',async()=>{const result=await runProductionSmoke({origin,fetcher:async url=>{if(url.endsWith('/api/health'))throw new Error('SECRET_PROVIDER_DATA');return fixture(url);}});assert.equal(result.ok,false);assert.doesNotMatch(JSON.stringify(result),/SECRET_PROVIDER_DATA/);await assert.rejects(runProductionSmoke({origin:'https://user:secret@champion.example'}),/HTTPS origin/);});
